# Generated by Django 6.0.3 on 2026-04-28 11:28

# Esta migración crea la tabla de preferencias de usuario.
# Django la usa para guardar la configuración personal asociada a cada cuenta.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(default='meta/llama-3.1-8b-instruct', max_length=120)),
                ('llm_max_tokens', models.IntegerField(default=1024)),
                ('llm_temperature', models.FloatField(default=0.7, help_text='Valor entre 0.0 y 2.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
