# Generated by Django 6.0.3 on 2026-05-16 11:05

# Añade el modelo LLM elegido por conversación.
# Si queda vacío, la app usa la preferencia global del usuario.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatia', '0004_messagefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Modelo LLM a usar para esta conversación (si está vacío usa la preferencia de usuario).', max_length=120, null=True),
        ),
    ]
