"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(path):
    """Load KEY=VALUE pairs from a local .env file into os.environ."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip())


def env_first(*names, default=''):
    """Return the first non-empty environment variable among provided names."""
    for name in names:
        value = os.getenv(name, '').strip()
        if value:
            return value
    return default


load_local_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2ooa$qfu6t^e$zp6+!eu+3z3a+ko@d+u01lxuzbbw$79)cg!8o'

# SECURITY WARNING: don't run with debug turned on in production!
# For local development we enable DEBUG so Django serves static files
# and error pages are easier to inspect. Remember to set DEBUG=False
# before deploying to production.
DEBUG = True

ALLOWED_HOSTS = ['juansv22.pythonanywhere.com', 'localhost', '127.0.0.1', '[::1]']

CSRF_TRUSTED_ORIGINS = ['https://juansv22.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chatia.context_processors.site_metrics',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# URL prefix for static files served by the web server
STATIC_URL = '/static/'
# Directory where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Additional directories to look for static files (keeps your app-level `static/`)
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_REDIRECT_URL = 'chatia:home'
LOGOUT_REDIRECT_URL = 'login'

LLM_BASE_URL = env_first('LLM_BASE_URL', default='https://integrate.api.nvidia.com/v1')
LLM_API_KEY = env_first('LLM_API_KEY', 'OPENAI_API_KEY', 'NVIDIA_API_KEY')
LLM_MODEL_1 = env_first('LLM_MODEL_1')
LLM_MODEL_2 = env_first('LLM_MODEL_2')
LLM_MODEL_3 = env_first('LLM_MODEL_3')
LLM_MODEL_4 = env_first('LLM_MODEL_4')
LLM_MODEL = env_first('LLM_MODEL', default=LLM_MODEL_1 or 'meta/llama-3.1-8b-instruct')
LLM_MAX_TOKENS = int(env_first('LLM_MAX_TOKENS', default='1024'))


def llm_model_info(model_value):
    preset_info = {
        'meta/llama-3.1-8b-instruct': {
            'label': 'Meta Llama 3.1 8B Instruct',
            'description': 'Equilibrado. Buena opción general para responder con rapidez y calidad razonable.',
        },
        'google/gemma-3n-e2b-it': {
            'label': 'Google Gemma 3n E2B IT',
            'description': 'Ligero y rápido. Bien para respuestas ágiles y pruebas cortas.',
        },
        'meta/llama-4-maverick-17b-128e-instruct': {
            'label': 'Meta Llama 4 Maverick 17B 128E Instruct',
            'description': 'Más potente y exigente. Útil si buscas mayor calidad en razonamiento y redacción.',
        },
        'openai/gpt-oss-120b': {
            'label': 'OpenAI GPT-OSS 120B',
            'description': 'Muy potente. Recomendado si quieres priorizar calidad, aunque puede ser más pesado.',
        },
    }
    info = preset_info.get(model_value)
    if info:
        return {
            'value': model_value,
            'label': info['label'],
            'description': info['description'],
        }
    return {
        'value': model_value,
        'label': model_value,
        'description': 'Modelo configurado en el entorno.',
    }


LLM_MODEL_CATALOG = [llm_model_info(model) for model in [LLM_MODEL_1, LLM_MODEL_2, LLM_MODEL_3, LLM_MODEL_4] if model]
if not LLM_MODEL_CATALOG:
    LLM_MODEL_CATALOG = [llm_model_info(LLM_MODEL)]
LLM_MODEL_CHOICES = [(model['value'], model['label']) for model in LLM_MODEL_CATALOG]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
